services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logchip
    ports:
      - "5432:5432"
    volumes:
      - logchip-db:/var/lib/postgresql/data

volumes:
  logchip-db:
